name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.13.5
  permission_handler: ^10.2.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  flutter_animate: ^4.2.0
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  http: ^1.2.2
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.jpg
    - assets/images/splashs.jpg
    - assets/images/welcome.jpg
    - assets/images/man1.png
    - assets/images/man2.png
    - assets/images/man3.png
    - assets/images/man4.png
    - assets/images/man1.jpg
    - assets/images/man2.jpg
    - assets/images/man3.jpg
    - assets/images/man4.jpg
    - assets/images/activ1.png
    - assets/images/activ2.png
    - assets/images/activ3.png
    - assets/images/activ4.png
    - assets/images/activv4.png
    - assets/images/robot.png
    - assets/images/profile.png
    - assets/images/voice.png
    - assets/images/health.png
    - assets/images/blobd.png
    - assets/images/blobu.png
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400